backend:
  name: github
  branch: master
  repo: G1-kiyo/v-blog-2.0

media_folder: static/img
public_folder: /img

collections:
  - name: 'post'
    label: 'post'
    folder: 'content/post'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{path}}/index'
    editor:
      preview: false
    fields:
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime" }
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Image", name: "img", widget: image}
      - {label: "AuthorImg", name: "authorimg", widget: image}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}      
